### ISSUE TITLE
Add preventDefault

### ISSUE THREAD

**Issue by rico345100** [jaszhix/react-markdown-editor-hybrid#1]
Hi, thanks for great module. Anyway when I wrap this component with &lt;form&gt;, every button in this module forcely try to submitting the form. Currently I just added preventDefault on form submit event, but I don't want to do that. Can you add preventDefault inside of clicking buttons in this module?

```javascript

import React, { Component } from 'react';
import MDEditor from 'react-markdown-editor-hybrid';

class MarkdownForm extends Component {
    ...
    render() {
        <form onSubmit={this.handleSubmit}>
            ...
            <MDEditor value={content} onChange={this.handleChange} />
        </form>
    }
}

```

**Comment by jaszhix** [comment]
Yes, I don't think that would be a problem. I'll take a look at that tonight. Thanks for pointing this out.

**Comment by jaszhix** [comment]
Added in 0.2.1.

**Comment by kaflan** [comment]
#aaa
